---
micronaut:
    application:
        name: zipkin-graal
jackson:
    module-scan: false
    bean-introspection-module: true

---
tracing:
  zipkin:
    enabled: true
    http:
      url: http://openzipkin:9411
    sampler:
      probability: 1

